name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - run: yarn install
    - run: yarn build
    - run: tree .
